msa/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

psipred_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^interface/msa/', include('msa.urls'), name='msa'),
    url(r'^interface/model/', include('model.urls'), name='model'),
    url(r'^interface/.*', include('interface.urls'), name='interface'),
    url(r'^interface', include('interface.urls'), name='interface'),
    # url(r'^structure/.*', include('struture.urls'), name='structure'),
    url(r'^admin/', admin.site.urls, name='admin'),
]

interface/models.py
from django.db import models


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-updating ``created``
    and ``modified`` fields.

    use with
    class Flavor(TimeStampedModel):
    """
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# Create your models here.
class Request(TimeStampedModel):
    email = models.EmailField(max_length=256, null=True, blank=True)
    password = models.CharField(max_length=25, null=True, blank=True)
    job_name = models.CharField(max_length=128, null=False, blank=False)
    input_data = models.TextField(null=False, blank=False)
    # sequence jobs
    psipred_job = models.BooleanField(null=False, default=False)
    disopred_job = models.BooleanField(null=False, default=False)
    memsatsvm_job = models.BooleanField(null=False, default=False)
    pgenthreader_job = models.BooleanField(null=False, default=False)
    mempack_job = models.BooleanField(null=False, default=False)
    genthreader_job = models.BooleanField(null=False, default=False)
    pdomthreader_job = models.BooleanField(null=False, default=False)
    bioserf_job = models.BooleanField(null=False, default=False)
    domserf_job = models.BooleanField(null=False, default=False)
    ffpred_job = models.BooleanField(null=False, default=False)
    metapsicov_job = models.BooleanField(null=False, default=False)
    dmp_job = models.BooleanField(null=False, default=False)
    dmpfold_job = models.BooleanField(null=False, default=False)
    s4pred_job = models.BooleanField(null=False, default=False)

    # structure jobs
    metsite_job = models.BooleanField(null=False, default=False)
    hspred_job = models.BooleanField(null=False, default=False)
    memembed_job = models.BooleanField(null=False, default=False)
    gentdb_job = models.BooleanField(null=False, default=False)


class ServerSuspension(models.Model):
    suspend = models.BooleanField(null=False, default=False)
    message = models.CharField(max_length=512, null=True, blank=False)
    allowed_ip = models.GenericIPAddressField(default="127.0.0.1", null=False,
                                              blank=False)


class ServerMessage(models.Model):
    display = models.BooleanField(null=False, default=False)
    message = models.CharField(max_length=512, null=True, blank=False)

interface/forms.py
from __future__ import unicode_literals

from django import forms
from django.forms.formsets import BaseFormSet, formset_factory
from django.utils.safestring import mark_safe

from .models import *


class PsipredForm(forms.ModelForm):
    psipred_job = forms.BooleanField(label="PSIPRED 4.0 (Predict Secondary Structure)", required=False,
                                     label_suffix = "",
                                     widget=forms.CheckboxInput(
                                      attrs={'value': '{{psipred_job}}',
                                             'checked': '{{psipred_checked}}'
                                             }))
    disopred_job = forms.BooleanField(label="DISOPRED3 (Disopred Prediction)", required=False,
                                     label_suffix = "",
                                      widget=forms.CheckboxInput(
                                       attrs={'value': '{{disopred_job}}',
                                              'checked': '{{disopred_checked}}'
                                              }))
    memsatsvm_job = forms.BooleanField(label="MEMSAT-SVM (Membrane Helix Prediction)", required=False,
                                     label_suffix = "",
                                       widget=forms.CheckboxInput(
                                        attrs={'value': '{{memsatsvm_job}}',
                                               'checked': '{{memsatsvm_checked}}'
                                               }))
    pgenthreader_job = forms.BooleanField(label="pGenTHREADER (Profile Based Fold Recognition)", required=False,
                                     label_suffix = "",
                                          widget=forms.CheckboxInput(
                                          attrs={'value': '{{pgenthreader_job}}',
                                                 'checked': '{{pgenthreader_checked}}'
                                                 }))
    mempack_job = forms.BooleanField(label="MEMPACK (TM Topology and Helix Packing)", required=False,
                                     label_suffix = "",
                                     widget=forms.CheckboxInput(
                                      attrs={'value': '{{mempack_job}}',
                                             'checked': '{{mempack_checked}}'
                                             }))
    genthreader_job = forms.BooleanField(label="GenTHREADER (Rapid Fold Recognition)", required=False,
                                     label_suffix = "",
                                         widget=forms.CheckboxInput(
                                          attrs={'value': '{{genthreader_job}}',
                                                'checked': '{{genthreader_checked}}'
                                                 }))
    dompred_job = forms.BooleanField(label="DomPred (Protein Domain Prediction)", required=False,
                                     label_suffix = "",
                                     widget=forms.CheckboxInput(
                                      attrs={'value': '{{dompred_job}}',
                                             'checked': '{{dompred_checked}}',
                                             'on-click': mark_safe('@this.fire("show_dompred")'),
                                             }))
    pdomthreader_job = forms.BooleanField(label="pDomTHREADER (Protein Domain Fold Recognition)", required=False,
                                     label_suffix = "",
                                          widget=forms.CheckboxInput(
                                          attrs={'value': '{{pdomthreader_job}}',
                                                 'checked': '{{pdomthreader_checked}}'
                                                 }))
    bioserf_job = forms.BooleanField(label="Bioserf 2.0 (Automated Homology Modelling)", required=False,
                                     label_suffix = "",
                                     widget=forms.CheckboxInput(
                                      attrs={'value': '{{bioserf_job}}',
                                             'checked': '{{bioserf_checked}}',
                                             'on-click': mark_safe("@this.fire('show_bioserf')"),
                                             }))
    domserf_job = forms.BooleanField(label="Domserf 2.1 (Automated Domain Homology Modelling)", required=False,
                                     label_suffix = "",
                                     widget=forms.CheckboxInput(
                                      attrs={'value': '{{domserf_job}}',
                                             'checked': '{{domserf_checked}}',
                                             'on-click': mark_safe("@this.fire('show_domserf')"),
                                            }))
    ffpred_job = forms.BooleanField(label="FFPred 3 (Eurkaryotic Function Prediction)", required=False,
                                     label_suffix = "",
                                    widget=forms.CheckboxInput(
                                      attrs={'value': '{{ffpred_job}}',
                                             'checked': '{{ffpred_checked}}',
                                             'on-click': mark_safe('@this.fire("show_ffpred")'),
                                             }))
    metapsicov_job = forms.BooleanField(label="MetaPSICOV 2.0 (Structural Contact Prediction)", required=False,
                                     label_suffix = "",
                                        widget=forms.CheckboxInput(
                                         attrs={'value': '{{metapsicov_job}}',
                                                'checked': '{{metapsicov_checked}}',
                                                'onclick' : "metAlert();",
                                                }))
    dmp_job = forms.BooleanField(label="DeepMetaPSICOV 1.0 (Structural Contact Prediction)", required=False,
                                     label_suffix = "",
                                        widget=forms.CheckboxInput(
                                         attrs={'value': '{{dmp_job}}',
                                                'checked': '{{dmp_checked}}',
                                                }))
    dmpfold_job = forms.BooleanField(label="DMPfold 1.0 Fast Mode (Protein Structure Prediction)", required=False,
                                     label_suffix = "",
                                        widget=forms.CheckboxInput(
                                         attrs={'value': '{{dmpfold_job}}',
                                                'checked': '{{dmpfold_checked}}',
                                                'onclick' : "dmpfoldAlert();",
                                                }))
    s4pred_job = forms.BooleanField(label="S4Pred 1.2 (Single Sequence SS prediction)", required=False,
                                     label_suffix = "",
                                        widget=forms.CheckboxInput(
                                         attrs={'value': '{{s4pred_job}}',
                                                'checked': '{{s4pred_checked}}',
                                                }))


    metsite_job = forms.BooleanField(label="Metsite (Protein-metal Ion Contact Prediction)", required=False,
                                     label_suffix = "",
                                     widget=forms.CheckboxInput(
                                      attrs={'value': '{{metsite_job}}',
                                             'checked': '{{metsite_checked}}',
                                             'on-click': mark_safe('@this.fire("show_metsite")'),
                                             }))
    hspred_job = forms.BooleanField(label="HSPred (Protein-Protein Hotspot Residue Prediction)", required=False,
                                     label_suffix = "",
                                    widget=forms.CheckboxInput(
                                      attrs={'value': '{{hspred_job}}',
                                             'checked': '{{hspred_checked}}',
                                             'on-click': mark_safe('@this.fire("show_hspred")'),
                                              }))
    memembed_job = forms.BooleanField(label="MEMEMBED (Membrane Protein Orientation Prediction)", required=False,
                                     label_suffix = "",
                                      widget=forms.CheckboxInput(
                                       attrs={'value': '{{memembed_job}}',
                                              'checked': '{{memembed_checked}}',
                                              'on-click': mark_safe('@this.fire("show_memembed")'),
                                              }))
    gentdb_job = forms.BooleanField(label="Generate TDB (Custom Generated Threading File)", required=False,
                                     label_suffix = "",
                                    widget=forms.CheckboxInput(
                                      attrs={'value': '{{gentdb_job}}',
                                             'checked': '{{gentdb_checked}}'
                                             }))

    input_data = forms.CharField(label="Protein Sequence",
                                 initial="Input Sequence",
                                 widget=forms.Textarea(
                                  attrs={'value': '{{sequence}}',
                                         'rows': '3'}))
    job_name = forms.CharField(widget=forms.TextInput(
                                attrs={'value': '{{name}}'}))
    email = forms.EmailField(label="Email (optional)", required=False, widget=forms.EmailInput(
                              attrs={'value': '{{email}}'}))

    class Meta:
        model = Request

interface/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext, loader
from django import forms
from django.conf import settings

from .forms import *


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def index(request):
    template = loader.get_template('interface/index.html')
    suspension_message = None
    server_message = None
    try:
        suspension_message = ServerSuspension.objects.all()[0]
    except:
        suspension_message = None

    try:
        server_message = ServerMessage.objects.all()[0]
    except:
        server_message = None



    passing_data = {}
    if suspension_message:
        passing_data = {"form": PsipredForm(),
                        "staging": settings.STAGING,
                        "debug": settings.DEBUG,
                        "production": settings.PRODUCTION,
                        "static_base_url": settings.STATIC_BASE_URL,
                        "suspend": suspension_message.suspend,
                        "suspend_message": suspension_message.message
                        }
        if server_message:
            passing_data["server_display"] = server_message.display
            passing_data["server_message"] = server_message.message
        else:
            passing_data["server_display"] = None
            passing_data["server_message"] = None

        client_ip = get_client_ip(request)
        print("CLIENT IP", client_ip)
        print("ALLOWED IP", suspension_message.allowed_ip)
        if client_ip == suspension_message.allowed_ip:
            passing_data['suspend'] = False
            passing_data['suspend_message'] = ''
    else:
        passing_data = {"form": PsipredForm(),
                        "staging": settings.STAGING,
                        "debug": settings.DEBUG,
                        "production": settings.PRODUCTION,
                        "static_base_url": settings.STATIC_BASE_URL,
                        "suspend": False,
                        "suspend_message": ''
                        }
        if server_message:
            passing_data["server_display"] = server_message.display
            passing_data["server_message"] = server_message.message
        else:
            passing_data["server_display"] = None
            passing_data["server_message"] = None

    return render(request, 'interface/index.html', passing_data)

interface/templates/interface/advanced_panel.html
{% load ractive_tags %}
{% load static %}
{% load bootstrap3 %}

{% templatetag openvariable %}#if bioserf_advanced === 1 {% templatetag closevariable %}
  <h4>Bioserf</h4>
  <strong>MODELLER Key:</strong>
  <input type="text" id="bioserf_modeller_key" name="bioserf_modeller_key">
{% templatetag openvariable %}/if{% templatetag closevariable %}

{% templatetag openvariable %}#if domserf_advanced === 1 {% templatetag closevariable %}
  <h4>Domserf</h4>
  <strong>MODELLER Key:</strong>
  <input type='text' id="domserf_modeller_key" name="domserf_modeller_key">
{% templatetag openvariable %}/if{% templatetag closevariable %}

{% templatetag openvariable %}#if dompred_advanced === 1 {% templatetag closevariable %}
  <h4>Dompred</h4>
  <strong>PSI-BLAST e-value cutoff:</strong>
  <input type='text' id="dompred_e_value_cutoff" name="dompred_e_value_cutoff" value="0.01"><br /><br />
  <strong>PSI-BLAST Iterations:</strong>
  <input type='text' id="dompred_psiblast_iterations" name="dompred_psiblast_iterations" value="5">
{% templatetag openvariable %}/if{% templatetag closevariable %}

{% templatetag openvariable %}#if ffpred_advanced === 1 {% templatetag closevariable %}
  <h4>FFpred</h4>
  <input type="radio" name="ffpred_selection" id="ffpred_human" value="human" checked> <label for="ffpred_human">Human Prediction</label><br />
  <input type="radio" name="ffpred_selection" id="ffpred_fly" value="fly"> <label for="ffpred_fly">Fly Prediction</label>
{% templatetag openvariable %}/if{% templatetag closevariable %}

{% templatetag openvariable %}#if metsite_advanced === 1 {% templatetag closevariable %}
  <h4>Metsite</h4>
  <strong>Select Metal:</strong><br />
  <select id="metsite_metal_type" name="metsite_metal_type" size="6">
    <option value="CA" selected="selected">Calcium</option>
    <option value="ZN">Zinc</option>
    <option value="MG">Magnesium</option>
    <option value="FE">Iron</option>
    <option value="CU">Copper</option>
    <option value="MN">Manganese</option>
  </select><br /><br />
  <strong>Chain ID:</strong>
  <input type='text' id="metsite_chain_id" name="metsite_chain_id" value="A"><br /><br />
  <strong>False Positive Rate:</strong>
  <select id="metsite_fpr" name="metsite_fpr" size="1">
    <option value="0">1%</option>
    <option value="1" selected="selected">5%</option>
    <option value="2">10%</option>
    <option value="3">20%</option>
  </select>
{% templatetag openvariable %}/if{% templatetag closevariable %}

{% templatetag openvariable %}#if hspred_advanced === 1 {% templatetag closevariable %}
  <h4>HSPred</h4>
  <strong>Protein 1:</strong>
  <input type='text' id="hspred_protein_1" name="hspred_protein_1" value="A"><br /><br />
  <strong>Protein 2:</strong>
  <input type='text' id="hspred_protein_2" name="hspred_protein_2" value="B">
{% templatetag openvariable %}/if{% templatetag closevariable %}

{% templatetag openvariable %}#if memembed_advanced === 1 {% templatetag closevariable %}
  <h4>Memembed</h4>
  <strong>Search Type:</strong>
  <select id="memembed_algorithm" name="memembed_algorithm" size="1">
    <option value="0" selected="selected">Genetic Algorithm</option>
    <option value="1">Grid Search</option>
    <option value="2">Direct</option>
    <option value="3">GA x 5</option>
  </select><br /><br />
  <strong>Target is Beta Barrel:</strong><br />
  <input type="radio" name="memembed_barrel" id="memembed_barrel_yes" value="true"> <label for="memembed_barrel_yes">Yes</label><br />
  <input type="radio" name="memembed_barrel" id="memembed_barrel_no" value="false" checked> <label for="memembed_barrel_no">No</label><br /><br />
  <strong>N-Terminal Location:</strong><br />
  <input type="radio" name="memembed_terminal" id="memembed_terminal_in" value="in"> <label for="memembed_terminal_in">Cytoplasmic</label><br />
  <input type="radio" name="memembed_terminal" id="memembed_terminal_out" value="out" checked> <label for="memembed_terminal_out">Extra Cellular</label><br /><br />
  <!--Helix boundaries:
  <input type='text' id="memembed_boundaries" name="memembed_boundaries">-->
{% templatetag openvariable %}/if{% templatetag closevariable %}

interface/templates/interface/base.html
{% extends 'adminlte/base.html' %}

{% load bootstrap3 %}
{% load static %}
{% load ractive_tags %}

{% block title %}PSIPRED Workbench{% endblock %}

{% block meta %}
    <meta charset="utf-8">
    <meta name="description" content="PSIPRED Protein Analysis Workbench">
    <meta name="keywords" content="Protein Folding,Bioinformatics,Secondary Structure,Homology Modelling,Proteins,amino acids,UCL,contact prediction,transmembrane helix prediction,fold recognition,binding side prediction,protein disorder">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="UCL Computer Science Department Bioinformatics Group">
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="{{ static_base_url }}{% static 'css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{{ static_base_url }}{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{{ static_base_url }}{% static 'css/ionicons.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{{ static_base_url }}{% static 'css/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />

    <link href="{{ static_base_url }}{% static 'css/psipred.css' %}" rel="stylesheet" type="text/css" />
    <link href="{{ static_base_url }}{% static 'css/biod3.css' %}" rel="stylesheet" type="text/css" />
    <link href="{{ static_base_url }}{% static 'css/dataTables.bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-6345502-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-6345502-1');
    </script>
{% endblock %}

{% block body_class %}
    skin-blue-light
{% endblock %}

{% block content_header %} {# remove header region, could add beta site info #}
{% endblock %}

{% block content %}{% endblock content%}

{% block javascript %}
    {# Load javascript #}
    <script src="{{ static_base_url }}{% static 'js/jquery.min.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/app.min.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/popper.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/ractive.min.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/ractive-events-tap.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/ractive-transitions-slide.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/biod3.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/clipboard.min.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/jszip.min.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/jszip-utils.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/FileSaver.min.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/msa.min.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/konami_code.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/data_tables_helper.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/jquery.slimscroll.min.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/fastclick.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/adminlte.min.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/alerts.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/3Dmol-nojquery.js' %}"></script>
    <script src="{{ static_base_url }}{% static 'js/psipred.js' %}"></script>

{% endblock %}

interface/templates/interface/resubmission.html
{% load ractive_tags %}
{% load static %}
{% load bootstrap3 %}
<br />
<form method="Post" class="form" intro="slide" outro="slide" on-submit="resubmit">
{% csrf_token %}
  <br />
  <h5>Select subsequence region</h5>
  Start Coordinate <input type="text" id="start_coord" class="sequence_coord" value="{% ractivetag "subsequence_start" %}"> - Stop Coordinate <input id="stop_coord" type="text" class="sequence_coord" value="{% ractivetag "subsequence_stop" %}">
  <div class="form-group">
    <div>
      <br />
      <h5>Choose prediction methods (hover for short description)</h5>
      <table class="full-width-table">
      <tr>
      <td>
        <input id="id_psipred_job" name="psipred_job" value="psipred_job" type="checkbox" checked="{% ractivetag "psipred_checked" %}">
        <label for="id_psipred_job">PSIPRED 4.0</label>
      </td>
      <td>
        <input id="id_disopred_job" name="disopred_job" value="disopred_job" type="checkbox" checked="{% ractivetag "disopred_checked" %}">
        <label for="id_disopred_job">DISOPRED3</label>
      </td>
      </tr>

      <tr>
      <td>
      <input id="id_memsat_job" name="memsat_job" value="memsat_job" type="checkbox" checked="{% ractivetag "memsat_checked" %}">
      <label for="id_memsat_job">MEMSAT-SVM</label>
      </td>
      <td>
      <input id="id_pgenthreader_job" name="pgenthreader_job" value="pgenthreader_job" type="checkbox" checked="{% ractivetag "pgenthreader_checked" %}">
      <label for="id_pgenthreader_job">pGenTHREADER</label>
      </td>
      </tr>

      <tr>
      <td>
        <input id="id_dmp_job" name="dmp_job" value="dmp_job" type="checkbox" checked="{% ractivetag "dmp_checked" %}">
        <label for="id_dmp_job">DeepMetaPSICOV</label>
      </td>
      <td>
        <input id="id_mempack_job" name="mempack_job" value="mempack_job" type="checkbox" checked="{% ractivetag "mempack_checked" %}">
        <label for="id_mempack_job">MEMPACK</label>
      </td>
      </tr>

      <tr>
      <td>
      <input id="id_genthreader_job" name="genthreader_job" value="genthreader_job" type="checkbox" checked="{% ractivetag "genthreader_checked" %}">
      <label for="id_genthreader_job">GenTHREADER</label>
      </td>
      <td>
      <input id="id_dompred_job" name="dompred_job" value="dompred_job" type="checkbox" checked="{% ractivetag "dompred_checked" %}">
      <label for="id_dompred_job">DomPred</label>
      </td>
      </tr>

      <tr>
      <td>
      <input id="id_pdomthreader_job" name="pdomthreader_job" value="pdomthreader_job" type="checkbox" checked="{% ractivetag "pdomthreader_checked" %}">
      <label for="id_pdomthreader_job">pDomTHREADER</label>
      </td>
      <td>
      <!--<i style="color:red" class="fa fa-times"></i>-->
      <input id="id_bioserf_job" name="bioserf_job" value="bioserf_job" type="checkbox" checked="{% ractivetag "bioserf_checked" %}">
      <label for="id_bioserf_job">Bioserf 2.0</label>
      </td>
      </tr>

      <tr>
      <td>
      <input id="id_domserf_job" name="domserf_job" value="domserf_job" type="checkbox" checked="{% ractivetag "domserf_checked" %}">
      <label for="id_domserf_job">Domserf 2.1</label>
      </td>
      <td>
      <input id="id_ffpred_job" name="ffpred_job" value="ffpred_job" type="checkbox" checked="{% ractivetag "ffpred_checked" %}">
      <label for="id_ffpred_job">FFPred 3</label>
      </td>
      </tr>

      <tr>
      <td>
      <input id="id_dmpfold_job" name="dmpfold_job" value="dmpfold_job" type="checkbox" checked="{% ractivetag "dmpfold_checked" %}">
      <label for="id_dmpfold_job">DMPfold</label>
      </td>
      <td>
      <input id="id_s4pred_job" name="s4pred_job" value="s4pred_job" type="checkbox" checked="{% ractivetag "s4pred_checked" %}">
      <label for="id_s4pred_job">S4Pred</label>
      </td>
      </tr>

      </table>
      <h5>Bioserf/Domserf MODELLER KEY</h5>
      <input type="text" id="bioserf_domserf_modeller_key" name="bioserf_domserf_modeller_key">
    </div>
  </div>
  <div class="text-right">
    <input value="Resubmit" type="submit" class="btn btn-primary" />
  </div>
  <br />
</form>